production:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=divulgador-api --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master
